server:
  port: 9000
#配置eureka server
eureka:
  instance:
    hostname: 127.0.0.1
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
#    register-with-eureka: false
#    fetch-registry: false
    service-url:
      defaultZone: http://127.0.0.1:8000/eureka/
  server:
    enable-self-preservation: false #关闭自我保护
    eviction-interval-timer-in-ms: 4000 #设置提出服务间隔
spring:
  application:
    name: eureka-server
