server:
  port: 9011

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-uf6ntoxzj7792dyq9co.mysql.rds.aliyuncs.com:3306/test?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 1qaz!QAZ
  application:
    name: service-product


# mybatis
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml # mapper映射文件路径
  type-aliases-package: com.product.entity

  # config-location:  # 指定mybatis的核心配置文件
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    lease-renewal-interval-in-seconds: 5 #向eureka注册服务的时间间隔
    lease-expiration-duration-in-seconds: 10 #续约到期时间

  client:
    service-url:
      defaultZone: http://127.0.0.1:9000/eureka/,http://127.0.0.1:8000/eureka/
